### ISSUE TITLE
💡 LED communication

### ISSUE THREAD

**Issue by AlenaNguyen** [FRCTeam3255/2024_Robot_Code#71]
```[tasklist]
### Tasks
- [x] When game piece is collected (5)
- [ ] https://github.com/FRCTeam3255/2024_Robot_Code/issues/142
- [ ] https://github.com/FRCTeam3255/2024_Robot_Code/issues/143
- [x] ~When endgame starts? (Don't know if we want this now that there's a sound for endgame) (3)~
- [x] ~Communcation for source drop location to HP? (3)~
- [x] Communication when pinned (panic button)??? (It's easy code and it'd be funny but probably not important) (1)
- [x] ~Confidence LEDs (LEDs getting brighter/changing color when closer to target)~
- [ ] https://github.com/FRCTeam3255/2024_Robot_Code/issues/141
```
